### ISSUE TITLE
Zoom out by box

### ISSUE THREAD

**Issue by Dot2122** [consbio/Leaflet.ZoomBox#10]
Hi,
First, thanks for your plugin, it’s very useful.
But I have one question; do you think it’s possible to do a zoom out by box?
Do you have some ideas?
Thanks.

**Comment by brendan-ward** [comment]
Hi @Dot2122 
I've never been a fan of zoom out by box, as the user interface seems counter-intuitive (what you draw on screen is not what you get).

This plugin relies on Leaflet's builtin `boxZoom` functionality, for which there appears to be no option to zoom out instead of in.

There is a suggestion about how to approach this [here](http://gis.stackexchange.com/questions/163953/box-zoom-out-in-leaflet-maps) - but I'm not particularly interested in adding box zoom out to this plugin.

**Comment by Dot2122** [comment]
Thanks for your answer.
I'll check the link.

Thanks.
